Repository Morel-Tech/square-connect-dart, pull requests merged in 2022-12, with the labels that each got.

#67 fix: CatalogDiscount percent to string
  lib/src/catalog/catalog_objects.dart
  lib/src/catalog/catalog_objects.g.dart
  pubspec.yaml
Labels: bug

#68 fix: catalog object without required params
  lib/src/catalog/catalog_objects.dart
  lib/src/catalog/catalog_objects.g.dart
  pubspec.yaml
Labels: bug

#75 refactor: move catalog objects to shared objects
  lib/square_connect.dart
  lib/src/catalog/catalog_enums.dart
  lib/src/catalog/catalog_objects.dart
  lib/src/catalog/catalog_objects.g.dart
  lib/src/shared_model/card.dart
  lib/src/shared_model/card_brand.dart
  lib/src/shared_model/card_prepaid_type.dart
  lib/src/shared_model/card_type.dart
  lib/src/shared_model/catalog_discount.dart
  lib/src/shared_model/catalog_discount.g.dart
  lib/src/shared_model/catalog_discount_type.dart
  lib/src/shared_model/catalog_id_mapping.dart
  lib/src/shared_model/catalog_id_mapping.g.dart
  lib/src/shared_model/catalog_info_response_limits.dart
  lib/src/shared_model/catalog_info_response_limits.g.dart
  lib/src/shared_model/catalog_item_product_type.dart
  lib/src/shared_model/catalog_measurement_unit.dart
  lib/src/shared_model/catalog_measurement_unit.g.dart
  lib/src/shared_model/catalog_object.g.dart
  lib/src/shared_model/catalog_object_batch.dart
  lib/src/shared_model/catalog_object_batch.g.dart
  lib/src/shared_model/catalog_pricing_rule.dart
  lib/src/shared_model/catalog_pricing_rule.g.dart
  lib/src/shared_model/catalog_pricing_type.dart
  lib/src/shared_model/catalog_product_set.dart
  lib/src/shared_model/catalog_product_set.g.dart
  lib/src/shared_model/catalog_query_type.dart
  lib/src/shared_model/catalog_tax.dart
  lib/src/shared_model/catalog_tax.g.dart
  lib/src/shared_model/discount_target_scope_type.dart
  lib/src/shared_model/inventory_alert_type.dart
  lib/src/shared_model/shared_model.dart
  lib/src/shared_model/standard_unit_description.dart
  lib/src/shared_model/standard_unit_description.g.dart
  lib/src/shared_model/standard_unit_description_group.dart
  lib/src/shared_model/standard_unit_description_group.g.dart
  lib/src/shared_model/tax_calculation_phase.dart
  lib/src/shared_model/tax_inclusion_type.dart
  lib/src/square_api_client.g.dart
Labels: refactoring

#83 feat: subscription endpoints
  .vscode/settings.json
  README.md
  bricks/function_object/brick.yaml
  lib/src/functions_model/cancel_subscription.dart
  lib/src/functions_model/cancel_subscription.g.dart
  lib/src/functions_model/create_subscription.dart
  lib/src/functions_model/create_subscription.g.dart
  lib/src/functions_model/delete_subscription_action.dart
  lib/src/functions_model/delete_subscription_action.g.dart
  lib/src/functions_model/functions_model.dart
  lib/src/functions_model/list_subscription_events.dart
  lib/src/functions_model/list_subscription_events.g.dart
  lib/src/functions_model/pause_subscription.dart
  lib/src/functions_model/pause_subscription.g.dart
  lib/src/functions_model/resume_subscription.dart
  lib/src/functions_model/resume_subscription.g.dart
  lib/src/functions_model/retrieve_subscription.dart
  lib/src/functions_model/retrieve_subscription.g.dart
  lib/src/functions_model/search_subscriptions.dart
  lib/src/functions_model/search_subscriptions.g.dart
  lib/src/functions_model/swap_plan.dart
  lib/src/functions_model/swap_plan.g.dart
  lib/src/functions_model/update_subscription.dart
  lib/src/functions_model/update_subscription.g.dart
  lib/src/shared_model/change_timing.dart
  lib/src/shared_model/search_subscriptions_filter.dart
  lib/src/shared_model/search_subscriptions_filter.g.dart
  lib/src/shared_model/search_subscriptions_query.dart
  lib/src/shared_model/search_subscriptions_query.g.dart
  lib/src/shared_model/shared_model.dart
  lib/src/shared_model/square_response.dart
  lib/src/shared_model/subscription.dart
  lib/src/shared_model/subscription.g.dart
  lib/src/shared_model/subscription_action.dart
  lib/src/shared_model/subscription_action.g.dart
  lib/src/shared_model/subscription_action_type.dart
  lib/src/shared_model/subscription_event.dart
  lib/src/shared_model/subscription_event.g.dart
  lib/src/shared_model/subscription_event_info.dart
  lib/src/shared_model/subscription_event_info.g.dart
  lib/src/shared_model/subscription_event_info_code.dart
  lib/src/shared_model/subscription_event_subscription_event_type.dart
  lib/src/shared_model/subscription_source.dart
  lib/src/shared_model/subscription_source.g.dart
  lib/src/shared_model/subscription_status.dart
  lib/src/square_api_client.dart
  lib/src/square_api_client.g.dart
  lib/src/webhook_model/subscription_created.dart
  lib/src/webhook_model/subscription_created.g.dart
  lib/src/webhook_model/subscription_updated.dart
  lib/src/webhook_model/subscription_updated.g.dart
  lib/src/webhook_model/webhook_model.dart
  pubspec.yaml
Labels: enhancement
